disabled_rules:
  - colon
  - comma
  - control_statement
  - identifier_name
  - force_cast
  - shorthand_operator
  - large_tuple
  - notification_center_detachment
  - nesting
  - function_parameter_count
  - trailing_whitespace

opt_in_rules:
  - empty_count

excluded:
  - Carthage
  - Pods

cyclomatic_complexity:
  warning: 25
  error: 50

line_length: 300

type_body_length:
  - 300 # warning
  - 600 # error

file_length:
  warning: 500
  error: 2500

function_body_length:
  - 200 # warning
  - 300 # error

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"]

force_try:
  severity: warning

analyzer_rules:
  - explicit_self

reporter: "xcode"
